-- MySQL Script generated by MySQL Workbench
-- Wed Aug  7 16:10:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Ecommerce
-- -----------------------------------------------------
-- Disable foreign key checks
SET FOREIGN_KEY_CHECKS = 0;
-- Enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;
-- -----------------------------------------------------
-- Schema Ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ecommerce`;
USE `Ecommerce` ;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Address` (
  `idAddress` INT AUTO_INCREMENT,
  `Address` LONGTEXT,
  `address_is_active` INT,
  `createdDate` DATETIME,
  `deletedDate` DATETIME,
  PRIMARY KEY (`idAddress`)
);

select * from Address;
-- drop table Address;

-- -----------------------------------------------------
-- Table `Ecommerce`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`User` (
  `idUser` INT AUTO_INCREMENT,
  `Name` VARCHAR(55),
  `Email` VARCHAR(220),
  `Phone` VARCHAR(15),
  `imageName` VARCHAR(100),
  `Password` VARCHAR(255),
  `Salt` VARCHAR(255),
  `user_is_active` INT,
  `Address_idAddress` INT,
  `createdDate` DATETIME,
  PRIMARY KEY (`idUser`),
  CONSTRAINT `fk_User_Address1`
    FOREIGN KEY (`Address_idAddress`)
    REFERENCES `Ecommerce`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

select * from User;
-- drop table User;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Admin` (
  `idAdmin` INT AUTO_INCREMENT,
  `AdminUserName` VARCHAR(45),
  `AdminPassword` VARCHAR(45),
  `createdDate` DATETIME,
  PRIMARY KEY (`idAdmin`),
  UNIQUE INDEX `AdminUserName_UNIQUE` (`AdminUserName` ASC) VISIBLE)
ENGINE = InnoDB;

select * from Admin;

-- -----------------------------------------------------
-- Table `Ecommerce`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Category` (
  `idCategory` INT AUTO_INCREMENT,
  `nameCategory` VARCHAR(45),
  `category_is_active` INT DEFAULT TRUE,
  `Admin_created` INT,
  `Admin_deleted` INT,
  `Admin_edited` INT,
  `createdDate` DATETIME,
  `deletedDate` DATETIME,
  PRIMARY KEY (`idCategory`),
  INDEX `fk_Category_Admin1_idx` (`Admin_created` ASC) VISIBLE,
  INDEX `fk_Category_Admin2_idx` (`Admin_deleted` ASC) VISIBLE,
  CONSTRAINT `fk_Category_Admin1`
    FOREIGN KEY (`Admin_created`)
    REFERENCES `Ecommerce`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Category_Admin2`
    FOREIGN KEY (`Admin_deleted`)
    REFERENCES `Ecommerce`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

select * from Category;
-- truncate table Category;

-- -----------------------------------------------------
-- Table `Ecommerce`.`Sub_Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Sub_Category` (
  `idSubcategory` INT AUTO_INCREMENT,
  `nameSubCategory` VARCHAR(100),
  `Category_idCategory` INT,
  `Sub_Category_is_delete` INT DEFAULT FALSE,
  `Admin_isCreated` INT,
  `Admin_isEdited` INT,
  `Admin_isDeleted` INT,
  `createdDate` DATETIME,
  `deletedDate` DATETIME,
  PRIMARY KEY (`idSubcategory`),
  INDEX `fk_Sub_Category_Category_idx` (`Category_idCategory` ASC) VISIBLE,
  INDEX `fk_Sub_Category_Admin1_idx` (`Admin_isCreated` ASC) VISIBLE,
  INDEX `fk_Sub_Category_Admin2_idx` (`Admin_isDeleted` ASC) VISIBLE,
  CONSTRAINT `fk_Sub_Category_Category`
    FOREIGN KEY (`Category_idCategory`)
    REFERENCES `Ecommerce`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sub_Category_Admin1`
    FOREIGN KEY (`Admin_isCreated`)
    REFERENCES `Ecommerce`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sub_Category_Admin2`
    FOREIGN KEY (`Admin_isDeleted`)
    REFERENCES `Ecommerce`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

select * from Sub_Category;
-- truncate table Sub_Category;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Products` (
  `idProducts` INT AUTO_INCREMENT,
  `nameProduct` VARCHAR(55),
  `Description` VARCHAR(255),
  `Price` INT,
  `Sub_Category_idSubcategory` INT,
  `product_is_active` INT DEFAULT TRUE,
  `admin_Created` INT,
  `admin_deleted` INT,
  `createdDate` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `deletedDate` DATETIME,
  PRIMARY KEY (`idProducts`),
  INDEX `fk_Products_Sub_Category1_idx` (`Sub_Category_idSubcategory` ASC) VISIBLE,
  INDEX `fk_Products_Admin1_idx` (`admin_Created` ASC) VISIBLE,
  INDEX `fk_Products_Admin2_idx` (`admin_deleted` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Sub_Category1`
    FOREIGN KEY (`Sub_Category_idSubcategory`)
    REFERENCES `Ecommerce`.`Sub_Category` (`idSubcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Admin1`
    FOREIGN KEY (`admin_Created`)
    REFERENCES `Ecommerce`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Admin2`
    FOREIGN KEY (`admin_deleted`)
    REFERENCES `Ecommerce`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

select * from Products;
-- truncate table Products;

-- -----------------------------------------------------
-- Table `Ecommerce`.`Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Rating` (
  `idRating` INT AUTO_INCREMENT,
  `productRating` INT NULL,
  `Products_idProducts` INT NOT NULL,
  `rated_time` DATETIME NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idRating`),
  INDEX `fk_Rating_Products1_idx` (`Products_idProducts` ASC) VISIBLE,
  INDEX `fk_Rating_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Rating_Products1`
    FOREIGN KEY (`Products_idProducts`)
    REFERENCES `Ecommerce`.`Products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rating_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Ecommerce`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`OrderIdTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`OrderIdTable` (
  `orderId` INT AUTO_INCREMENT,
  `Order_date` DATETIME NULL,
  `User_idUser` INT NOT NULL,
  `Address_idAddress` INT NOT NULL,
  PRIMARY KEY (`orderId`),
  INDEX `fk_OrderIdTable_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_OrderIdTable_Address1_idx` (`Address_idAddress` ASC) VISIBLE,
  CONSTRAINT `fk_OrderIdTable_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Ecommerce`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderIdTable_Address1`
    FOREIGN KEY (`Address_idAddress`)
    REFERENCES `Ecommerce`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`OrderDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`OrderDetails` (
  `idOrderDetails` INT NULL AUTO_INCREMENT,
  `OrderIdTable_orderId` INT NULL,
  `Products_idProducts` INT NULL,
  `quantity` INT NULL,
  `totalPrice` INT NULL,
  PRIMARY KEY (`idOrderDetails`),
  INDEX `fk_OrderDetails_OrderIdTable1_idx` (`OrderIdTable_orderId` ASC) VISIBLE,
  INDEX `fk_OrderDetails_Products1_idx` (`Products_idProducts` ASC) VISIBLE,
  CONSTRAINT `fk_OrderDetails_OrderIdTable1`
    FOREIGN KEY (`OrderIdTable_orderId`)
    REFERENCES `Ecommerce`.`OrderIdTable` (`orderId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderDetails_Products1`
    FOREIGN KEY (`Products_idProducts`)
    REFERENCES `Ecommerce`.`Products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`productImage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`productImage` (
  `idproductImage` INT AUTO_INCREMENT,
  `imageName` VARCHAR(100) NULL,
  `Products_idProducts` INT NOT NULL,
  `createdDate` DATETIME NULL,
  PRIMARY KEY (`idproductImage`),
  INDEX `fk_productImage_Products1_idx` (`Products_idProducts` ASC) VISIBLE,
  CONSTRAINT `fk_productImage_Products1`
    FOREIGN KEY (`Products_idProducts`)
    REFERENCES `Ecommerce`.`Products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ecommerce`.`Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ecommerce`.`Cart` (
  `idCart` INT AUTO_INCREMENT,
  `quantity` INT NULL,
  `Products_idProducts` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `createdDate` DATETIME NULL,
  `sessionId` VARCHAR(100) NULL,
  PRIMARY KEY (`idCart`),
  INDEX `fk_Cart_Products1_idx` (`Products_idProducts` ASC) VISIBLE,
  INDEX `fk_Cart_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Cart_Products1`
    FOREIGN KEY (`Products_idProducts`)
    REFERENCES `Ecommerce`.`Products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cart_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Ecommerce`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
